In [1]:
# https://towardsdatascience.com/adversarial-machine-learning-mitigation-adversarial-learning-9ae04133c137
import cleverhans
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from keras.utils import np_utils
from cleverhans.future.tf2.attacks import fast_gradient_method

In [2]:
# new Data preparation

# Training Dataset
data = pd.read_csv("./dataset/UNSW_2018_IoT_Botnet_Final_10_best_Training.csv")

x_features = data[['seq','stddev','N_IN_Conn_P_SrcIP', 'min', 'state_number', 'mean', 'N_IN_Conn_P_DstIP',
       'drate', 'srate', 'max', 'category', 'subcategory']]

# Label Encoding the target columns
le = LabelEncoder()
x_features['category'] = le.fit_transform(x_features['category'])
x_features['subcategory'] = le.fit_transform(x_features['subcategory'])

x = x_features.values
x = preprocessing.scale(x)
y = data['attack'].values

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

y_train_cat = np_utils.to_categorical(y_train)
y_test_cat = np_utils.to_categorical(y_test)

C:\Users\sumsu\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\sumsu\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [3]:
model = tf.keras.Sequential([
        tf.keras.layers.Dense(200, input_dim=x.shape[1], activation=tf.nn.relu),
        tf.keras.layers.Dense(500, activation=tf.nn.relu),
        tf.keras.layers.Dense(200, activation=tf.nn.relu),
        tf.keras.layers.Dense(len(np.unique(y))),
        # We seperate the activation layer to be able to access
        # the logits of the previous layer later
        tf.keras.layers.Activation(tf.nn.softmax)
        ])

model.compile(optimizer='adam',
              loss= 'categorical_crossentropy',
              metrics=['accuracy'])

In [4]:
model.fit(X_train, y_train_cat, epochs=10, validation_split=0.2)
test_loss, test_acc = model.evaluate(X_test, y_test_cat)
print('Test accuracy:', test_acc)

Epoch 1/10
58697/58697 [==============================] - 248s 4ms/step - loss: 0.0015 - accuracy: 0.9999 - val_loss: 9.0154e-04 - val_accuracy: 1.0000
Epoch 2/10
58697/58697 [==============================] - 240s 4ms/step - loss: 6.8380e-04 - accuracy: 1.0000 - val_loss: 0.0021 - val_accuracy: 1.0000
Epoch 3/10
58697/58697 [==============================] - 240s 4ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 0.0014 - val_accuracy: 1.0000
Epoch 4/10
58697/58697 [==============================] - 241s 4ms/step - loss: 8.8946e-04 - accuracy: 1.0000 - val_loss: 3.2978e-05 - val_accuracy: 1.0000
Epoch 5/10
58697/58697 [==============================] - 243s 4ms/step - loss: 2.3500e-04 - accuracy: 1.0000 - val_loss: 0.0051 - val_accuracy: 1.0000
Epoch 6/10
58697/58697 [==============================] - 245s 4ms/step - loss: 4.2426e-04 - accuracy: 1.0000 - val_loss: 0.0014 - val_accuracy: 1.0000
Epoch 7/10
58697/58697 [==============================] - 245s 4ms/step - loss: 6.0066e-

In [5]:
y_pred = model.predict(X_test)
y_pred=np.argmax(y_pred, axis=1)
cm_org = confusion_matrix(y_test, y_pred)
print("*"*50)
print("Original confusion matrix")
print(cm_org)

18343/18343 [==============================] - 24s 1ms/step
**************************************************
Original confusion matrix
[[    78      0]
 [     4 586882]]


In [6]:
# Import the attack
#The attack requires the model to ouput the logits
logits_model = tf.keras.Model(model.input, model.layers[-1].output)

epsilon = 0.1
adv_fgsm_x = fast_gradient_method(logits_model,
                                  X_test,
                                  epsilon,
                                  np.inf,
                                  targeted=False)

In [7]:
y_pred = model.predict(adv_fgsm_x)
y_pred=np.argmax(y_pred, axis=1)
cm_adv = confusion_matrix(y_test, y_pred)
print("*"*20)
print("Attacked confusion matrix")
print(cm_adv)

18343/18343 [==============================] - 24s 1ms/step
********************
Attacked confusion matrix
[[    78      0]
 [     5 586881]]


In [8]:
print(adv_fgsm_x)

tf.Tensor(
[[ 0.93217436  0.68358818  0.71545303 ...  0.18634968  0.75246724
   0.84493152]
 [ 1.19786642 -0.29750283 -0.06354877 ...  0.86415027  0.75246724
   0.84493152]
 [-0.61596743 -0.69937109 -0.18654906 ...  0.60261328 -0.83068184
   0.84493152]
 ...
 [-1.30185037  0.78048368  0.71545303 ...  0.2139157  -0.83068184
  -0.86685956]
 [ 1.62724093  1.26222984  0.71545303 ...  0.54672893 -0.83068184
   0.84493152]
 [-0.56280527 -1.10368447  0.71545303 ... -1.6224652   0.75246724
  -0.86685956]], shape=(586964, 12), dtype=float64)
